name: Deploy Frontend

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Navigate to the front-end directory
      - name: Install Dependencies and Build
        run: |
          cd front-end
          npm ci        # Install dependencies using package-lock.json
          npm run build  # Build the project (if build script exists)
        
      # Run tests (optional)
      - run: |
          cd front-end
          npm test  # Run tests

      # Deploy the build output to GitHub Pages
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npx gh-pages -d front-end/build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
